apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "word-dispenser.fullname" . }}
  labels:
    {{- include "word-dispenser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "word-dispenser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "word-dispenser.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASE_PATH
              value: /{{ .Release.Namespace }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ .Release.Namespace }}/health
              port: http
          readinessProbe:
            httpGet:
              path: /{{ .Release.Namespace }}/health
              port: http
          volumeMounts:
            - mountPath: /etc/words-dispenser
              name: word-list
      volumes:
        - name: word-list
          configMap:
            defaultMode: 420
            name: word-list
